server:
  port: 9091
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db5
    username: root
    password: root
mybatis:
  type-aliases-package: com.letv.pojo